# Generated by Django 4.2.4 on 2023-09-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('formacao', models.CharField(choices=[('G', 'Graduação'), ('M', 'Mestrado'), ('D', 'Doutorado')], default='G', max_length=1)),
            ],
        ),
    ]
