# Generated by Django 4.2.4 on 2023-09-02 18:45

import apps.professores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, validators=[apps.professores.models.ProfessorModel.validate])),
                ('email', models.EmailField(max_length=100)),
                ('formacao', models.CharField(choices=[('G', 'Graduação'), ('M', 'Mestrado'), ('D', 'Doutorado')], default='G', max_length=1)),
                
            ],
        ),
    ]
