# Generated by Django 4.2.4 on 2023-09-02 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_alter_curso_codigo_curso'),
        ('professores', '0002_alter_professor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
    ]
