# Generated by Django 4.2.4 on 2023-09-07 00:03

import apps.professores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0002_alter_professormodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professormodel',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[apps.professores.models.ProfessorModel.validate]),
        ),
        migrations.AlterField(
            model_name='professormodel',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
