# Generated by Django 4.2.4 on 2023-09-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0003_professor_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='curso',
        ),
    ]
