# Generated by Django 4.2.4 on 2023-09-02 14:42

import apps.professores.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_alter_curso_codigo_curso'),
        ('professores', '0005_professor_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='cpf',
            field=models.CharField(default='04656326020', max_length=11, unique=True, validators=[apps.professores.models.Professor.validate]),
        ),
        migrations.AlterField(
            model_name='professor',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
    ]
