# Generated by Django 4.2.4 on 2023-09-02 14:46

import apps.professores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0006_professor_cpf_alter_professor_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[apps.professores.models.Professor.validate]),
        ),
    ]
