# Generated by Django 4.2.4 on 2023-09-02 18:29

import apps.alunos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[apps.alunos.models.AlunoModel.validate])),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.cursomodel')),
            ],
        ),
    ]
