# Generated by Django 4.2.4 on 2023-09-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alunomodel',
            old_name='curso',
            new_name='professor_do_curso',
        ),
    ]
