# Generated by Django 4.2.4 on 2023-09-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_rename_curso_alunomodel_professor_do_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alunomodel',
            old_name='professor_do_curso',
            new_name='curso',
        ),
    ]
