# Generated by Django 4.2.4 on 2023-09-05 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('alunos', '0003_rename_professor_do_curso_alunomodel_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunomodel',
            name='curso_entrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alunos_entrada', to='cursos.cursomodel'),
        ),
    ]
