# Generated by Django 4.2.4 on 2023-09-02 14:00

import apps.alunos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_alter_aluno_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[apps.alunos.models.Aluno.validate]),
        ),
    ]
