# Generated by Django 4.2.4 on 2023-09-05 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('alunos', '0004_alunomodel_curso_entrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunomodel',
            name='curso_entrada',
        ),
        migrations.AddField(
            model_name='alunomodel',
            name='curso_matriculado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alunos_matriculado', to='cursos.cursomodel'),
        ),
    ]
