# Generated by Django 4.2.4 on 2023-09-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_remove_alunomodel_curso_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunomodel',
            name='curso_matriculado',
        ),
    ]
