# Generated by Django 4.2.4 on 2023-09-02 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(max_length=150)),
                ('codigo_curso', models.CharField(max_length=6, unique=True)),
                ('carga_horaria', models.CharField(choices=[('45', '45 Horas'), ('60', '60 Horas'), ('90', '90 Horas')], max_length=2)),
                ('descricao', models.CharField(max_length=500)),
                ('turno', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], max_length=1)),
                ('nivel', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], default='B', max_length=1)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professores.professormodel')),
            ],
        ),
    ]
