# Generated by Django 4.2.4 on 2023-09-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_carga_horaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.CharField(choices=[('45', '45 Horas'), ('60', '60 Horas'), ('90', '90 Horas')], max_length=2),
        ),
    ]
