# Generated by Django 4.2.4 on 2023-09-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_curso_carga_horaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='codigo_curso',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
